name: apk-builder

mem: 128M

framework:
  type: node

hooks:
  post-staging:
  - ./install_tools.sh
  pre-running:
  # - (tools=$STACKATO_FILESYSTEM_TOOLS ; PATH=$tools/android-sdk-linux/tools:$tools/android-sdk-linux/platform-tools:$pwd/bin/jdk1.7.0_40/bin:$PATH ; android update project -p template -t android-18)

processes:
  web: (tools=$STACKATO_FILESYSTEM_TOOLS ; PATH=$tools/apache-ant-1.9.2/bin:$pwd/bin/jdk1.7.0_40/bin:$tools/android-sdk-linux/tools:$tools/android-sdk-linux/platform-tools:$PATH ; node lib/server.js)

services:
  build: filesystem
  cache: filesystem
  tools: filesystem

ignores: ['node_modules', '.git', 'cache']